version: "3"

services: 

  webapp:
    build: webapp/
    restart: always
    ports: 
      - "8080:8080"
    links:
      - tarantoolapp
  
  tarantoolapp:
    build: tarantoolapp/
    restart: always
    command: tarantool /opt/tarantool/notes.lua
    expose: 
      - "3301"